const fs = require('fs');
const path = require('path');

const transPath = path.join(__dirname, 'utils', 'translations.ts');
let transCode = fs.readFileSync(transPath, 'utf8');

const newTranslations = {
  es: `    settingsPage: {
      optionsTitle: 'Opciones',
      supportBtn: 'Configurar Soporte Técnico',
      companyDataTitle: 'Datos de la Empresa',
      companyDataDesc: 'Para Recibos y Legajos',
      companyNameLabel: 'Nombre de la Empresa (Título App)',
      publicPhoneLabel: 'Teléfono Público',
      brandLabel: 'Marca',
      companyIdLabel: 'ID Empresa (Legajo)',
      bankNamesLabel: 'Nombres de banco o cuentas bancarias',
      accountNumberLabel: 'Numero de cuenta o alias de la empresa',
      boldBtn: 'Negrita',
      sizeNormal: 'Normal',
      sizeMedium: 'Med.',
      sizeLarge: 'Gnd.',
      printStylesTitle: 'Estilos de Impresión (Resaltado)',
      printNameLabel: 'Nombre de Empresa',
      printIdLabel: 'ID Legal (NIT/RUC)',
      printPhoneLabel: 'Teléfono Soporte',
      printMarginTitle: 'Margen Final (Cola del Recibo)',
      printMarginDesc: 'Largo del papel sobrante',
      lines: 'LÍNEAS',
      saveCompanyData: 'GUARDAR DATOS DE EMPRESA',
      bancardTitle: 'Integración de Bancard (Cobro QR)',
      bancardDesc: 'Configuración de Credenciales para Cobro Móvil',
      shopIdLabel: 'Código de Comercio (Shop ID)',
      publicKeyLabel: 'Clave Pública (Public Key)',
      privateKeyLabel: 'Clave Privada (Private Key)',
      saveBancard: 'GUARDAR CREDENCIALES DE BANCARD',
      saving: 'GUARDANDO...',
      syncZoneTitle: 'Zona de Estabilización',
      syncZoneDesc: 'Solución de Sincronización',
      connStable: 'Conexión Estable',
      connStableDesc: 'La App tiene acceso verificado a los servidores.',
      connOffline: 'Sin Internet Real',
      connOfflineDesc: 'Detectamos problemas de conexión. Los datos se guardarán localmente.',
      forceSyncBtn: 'FORZAR SINCRONIZACIÓN',
      syncing: 'SINCRONIZANDO...',
      clearQueueBtn: 'LIMPIAR COLA',
      repairSyncBtn: 'REPARAR PROBL. SINCRONIZACIÓN',
      deepUpdateBtn: 'ACTUALIZACIÓN PROFUNDA',
      syncWarning: '* Use "Forzar Sincronización" si sus pagos no aparecen. Use "Reparación Profunda" solo si el problema persiste.',
      currencyFormatTitle: 'Formato de Moneda',
      dotFormat: 'PUNTO DE MIL',
      commaFormat: 'PUNTO DE COMA',
      printerConfigTitle: 'Configuración de Impresora',
      searchPrinterBtn: 'BUSCAR IMPRESORA',
      searching: 'BUSCANDO...',
      testPrintBtn: 'PROBAR IMPRESIÓN',
      printerWarning: '* Conecte su impresora térmica vía Bluetooth para imprimir recibos automáticamente tras cada cobro.',
      linked: 'Vinculado:',
      saveAndExit: 'GUARDAR Y SALIR'
    },`,
  en: `    settingsPage: {
      optionsTitle: 'Options',
      supportBtn: 'Configure Tech Support',
      companyDataTitle: 'Company Data',
      companyDataDesc: 'For Receipts and Records',
      companyNameLabel: 'Company Name (App Title)',
      publicPhoneLabel: 'Public Phone',
      brandLabel: 'Brand',
      companyIdLabel: 'Company ID (Tax ID)',
      bankNamesLabel: 'Bank names or accounts',
      accountNumberLabel: 'Account number or company alias',
      boldBtn: 'Bold',
      sizeNormal: 'Normal',
      sizeMedium: 'Med.',
      sizeLarge: 'Lrg.',
      printStylesTitle: 'Print Styles (Highlighting)',
      printNameLabel: 'Company Name',
      printIdLabel: 'Legal ID (Tax ID)',
      printPhoneLabel: 'Support Phone',
      printMarginTitle: 'Final Margin (Receipt Tail)',
      printMarginDesc: 'Length of excess paper',
      lines: 'LINES',
      saveCompanyData: 'SAVE COMPANY DATA',
      bancardTitle: 'Bancard Integration (QR Payment)',
      bancardDesc: 'Mobile Payment Credentials Configuration',
      shopIdLabel: 'Shop ID',
      publicKeyLabel: 'Public Key',
      privateKeyLabel: 'Private Key',
      saveBancard: 'SAVE BANCARD CREDENTIALS',
      saving: 'SAVING...',
      syncZoneTitle: 'Stabilization Zone',
      syncZoneDesc: 'Synchronization Solution',
      connStable: 'Stable Connection',
      connStableDesc: 'The App has verified access to the servers.',
      connOffline: 'No Real Internet',
      connOfflineDesc: 'We detected connection problems. Data will be saved locally.',
      forceSyncBtn: 'FORCE SYNCHRONIZATION',
      syncing: 'SYNCING...',
      clearQueueBtn: 'CLEAR QUEUE',
      repairSyncBtn: 'REPAIR SYNC PROBLEM',
      deepUpdateBtn: 'DEEP UPDATE',
      syncWarning: '* Use "Force Synchronization" if your payments do not appear. Use "Deep Update" only if the problem persists.',
      currencyFormatTitle: 'Currency Format',
      dotFormat: 'THOUSAND DOT',
      commaFormat: 'THOUSAND COMMA',
      printerConfigTitle: 'Printer Configuration',
      searchPrinterBtn: 'SEARCH PRINTER',
      searching: 'SEARCHING...',
      testPrintBtn: 'TEST PRINT',
      printerWarning: '* Connect your thermal printer via Bluetooth to automatically print receipts.',
      linked: 'Linked:',
      saveAndExit: 'SAVE AND EXIT'
    },`,
  pt: `    settingsPage: {
      optionsTitle: 'Opções',
      supportBtn: 'Configurar Suporte Técnico',
      companyDataTitle: 'Dados da Empresa',
      companyDataDesc: 'Para Recibos e Registros',
      companyNameLabel: 'Nome da Empresa (Título do App)',
      publicPhoneLabel: 'Telefone Público',
      brandLabel: 'Marca',
      companyIdLabel: 'ID da Empresa (CNPJ)',
      bankNamesLabel: 'Nomes de bancos ou contas',
      accountNumberLabel: 'Número da conta ou alias da empresa',
      boldBtn: 'Negrito',
      sizeNormal: 'Normal',
      sizeMedium: 'Méd.',
      sizeLarge: 'Grd.',
      printStylesTitle: 'Estilos de Impressão (Destaque)',
      printNameLabel: 'Nome da Empresa',
      printIdLabel: 'ID Legal (CNPJ)',
      printPhoneLabel: 'Telefone de Suporte',
      printMarginTitle: 'Margem Final (Fim do Recibo)',
      printMarginDesc: 'Comprimento do papel excedente',
      lines: 'LINHAS',
      saveCompanyData: 'SALVAR DADOS DA EMPRESA',
      bancardTitle: 'Integração Bancard (Pagamento QR)',
      bancardDesc: 'Configuração de Credenciais de Pagamento Móvel',
      shopIdLabel: 'Código da Loja (Shop ID)',
      publicKeyLabel: 'Chave Pública (Public Key)',
      privateKeyLabel: 'Chave Privada (Private Key)',
      saveBancard: 'SALVAR CREDENCIAIS BANCARD',
      saving: 'SALVANDO...',
      syncZoneTitle: 'Zona de Estabilização',
      syncZoneDesc: 'Solução de Sincronização',
      connStable: 'Conexão Estável',
      connStableDesc: 'O aplicativo tem acesso verificado aos servidores.',
      connOffline: 'Sem Internet Real',
      connOfflineDesc: 'Detectamos problemas de conexão. Os dados serão salvos localmente.',
      forceSyncBtn: 'FORÇAR SINCRONIZAÇÃO',
      syncing: 'SINCRONIZANDO...',
      clearQueueBtn: 'LIMPAR FILA',
      repairSyncBtn: 'REPARAR PROBLEMA DE SYNC',
      deepUpdateBtn: 'ATUALIZAÇÃO PROFUNDA',
      syncWarning: '* Use "Forçar Sincronização" se seus pagamentos não aparecerem. Use "Atualização Profunda" apenas se o problema persistir.',
      currencyFormatTitle: 'Formato de Moeda',
      dotFormat: 'PONTO DE MILHAR',
      commaFormat: 'VÍRGULA DE MILHAR',
      printerConfigTitle: 'Configuração de Impressora',
      searchPrinterBtn: 'BUSCAR IMPRESSORA',
      searching: 'BUSCANDO...',
      testPrintBtn: 'TESTAR IMPRESSÃO',
      printerWarning: '* Conecte sua impressora térmica via Bluetooth para imprimir recibos automaticamente.',
      linked: 'Vinculado:',
      saveAndExit: 'SALVAR E SAIR'
    },`,
  fr: `    settingsPage: {
      optionsTitle: 'Options',
      supportBtn: 'Configurer le Support Technique',
      companyDataTitle: 'Données de l\\'Entreprise',
      companyDataDesc: 'Pour Reçus et Dossiers',
      companyNameLabel: 'Nom de l\\'Entreprise (Titre de l\\'App)',
      publicPhoneLabel: 'Téléphone Public',
      brandLabel: 'Marque',
      companyIdLabel: 'ID Entreprise (SIRET)',
      bankNamesLabel: 'Noms de banque ou comptes',
      accountNumberLabel: 'Numéro de compte ou alias',
      boldBtn: 'Gras',
      sizeNormal: 'Normal',
      sizeMedium: 'Moy.',
      sizeLarge: 'Grd.',
      printStylesTitle: 'Styles d\\'Impression (Mise en valeur)',
      printNameLabel: 'Nom de l\\'Entreprise',
      printIdLabel: 'ID Légal (SIRET)',
      printPhoneLabel: 'Téléphone Support',
      printMarginTitle: 'Marge Finale (Fin de Reçu)',
      printMarginDesc: 'Longueur de papier excédentaire',
      lines: 'LIGNES',
      saveCompanyData: 'ENREGISTRER',
      bancardTitle: 'Intégration Bancard (Paiement QR)',
      bancardDesc: 'Configuration des Identifiants de Paiement Mobile',
      shopIdLabel: 'Code Boutique (Shop ID)',
      publicKeyLabel: 'Clé Publique (Public Key)',
      privateKeyLabel: 'Clé Privée (Private Key)',
      saveBancard: 'ENREGISTRER IDENTIFIANTS',
      saving: 'ENREGISTREMENT...',
      syncZoneTitle: 'Zone de Stabilisation',
      syncZoneDesc: 'Solution de Synchronisation',
      connStable: 'Connexion Stable',
      connStableDesc: 'L\\'Appli a un accès vérifié aux serveurs.',
      connOffline: 'Pas d\\'Internet Réel',
      connOfflineDesc: 'Nous avons détecté des problèmes de connexion. Les données seront sauvegardées localement.',
      forceSyncBtn: 'FORCER LA SYNCHRONISATION',
      syncing: 'SYNCHRONISATION...',
      clearQueueBtn: 'VIDER LA FILE',
      repairSyncBtn: 'RÉPARER LE PROBLÈME DE SYNC',
      deepUpdateBtn: 'MISE À JOUR PROFONDE',
      syncWarning: '* Utilisez "Forcer la Synchronisation" si vos paiements n\\'apparaissent pas.',
      currencyFormatTitle: 'Format de Devise',
      dotFormat: 'POINT DES MILLIERS',
      commaFormat: 'VIRGULE DES MILLIERS',
      printerConfigTitle: 'Configuration de l\\'Imprimante',
      searchPrinterBtn: 'CHERCHER IMPRIMANTE',
      searching: 'RECHERCHE...',
      testPrintBtn: 'TESTER L\\'IMPRESSION',
      printerWarning: '* Connectez votre imprimante thermique via Bluetooth pour imprimer des reçus automatiquement.',
      linked: 'Lié:',
      saveAndExit: 'ENREGISTRER ET QUITTER'
    },`
};

for (const lang of ['es', 'en', 'pt', 'fr']) {
  const regexStr = '(' + lang + ':\\s*\\{\\s*common:)';
  const regex = new RegExp(regexStr, 'g');
  if (transCode.match(regex)) {
    transCode = transCode.replace(regex, "$1\\n" + newTranslations[lang]);
  }
}

fs.writeFileSync(transPath, transCode, 'utf8');

const compPath = path.join(__dirname, 'components', 'Settings.tsx');
let compCode = fs.readFileSync(compPath, 'utf8');

const replacements = [
  ['>Opciones<', '>{t.settingsPage?.optionsTitle || "Opciones"}<'],
  ['>Configuración Regional<', '>{t.settings.title || "Configuración Regional"}<'],
  ['>CONFIGURAR SOPORTE TÉCNICO<', '>{t.settingsPage?.supportBtn || "CONFIGURAR SOPORTE TÉCNICO"}<'],
  ['>Datos de la Empresa<', '>{t.settingsPage?.companyDataTitle || "Datos de la Empresa"}<'],
  ['>Para Recibos y Legajos<', '>{t.settingsPage?.companyDataDesc || "Para Recibos y Legajos"}<'],
  ['>Nombre de la Empresa (Título App)<', '>{t.settingsPage?.companyNameLabel || "Nombre de la Empresa (Título App)"}<'],
  ['>Teléfono Público<', '>{t.settingsPage?.publicPhoneLabel || "Teléfono Público"}<'],
  ['>Marca<', '>{t.settingsPage?.brandLabel || "Marca"}<'],
  ['>ID Empresa (Legajo)<', '>{t.settingsPage?.companyIdLabel || "ID Empresa (Legajo)"}<'],
  ['>Nombres de banco o cuentas bancarias<', '>{t.settingsPage?.bankNamesLabel || "Nombres de banco o cuentas bancarias"}<'],
  ['>Numero de cuenta o alias de la empresa<', '>{t.settingsPage?.accountNumberLabel || "Numero de cuenta o alias de la empresa"}<'],
  ['> Negrita<', '>{t.settingsPage?.boldBtn || "Negrita"}<'],
  ['>Normal<', '>{t.settingsPage?.sizeNormal || "Normal"}<'],
  ['>Med.<', '>{t.settingsPage?.sizeMedium || "Med."}<'],
  ['>Gnd.<', '>{t.settingsPage?.sizeLarge || "Gnd."}<'],
  ['>Mediano<', '>{t.settingsPage?.sizeMedium || "Mediano"}<'],
  ['>Grande<', '>{t.settingsPage?.sizeLarge || "Grande"}<'],
  ['>Estilos de Impresión (Resaltado)<', '>{t.settingsPage?.printStylesTitle || "Estilos de Impresión"}<'],
  ['>Nombre de Empresa<', '>{t.settingsPage?.printNameLabel || "Nombre de Empresa"}<'],
  ['>ID Legal (NIT/RUC)<', '>{t.settingsPage?.printIdLabel || "ID Legal (NIT/RUC)"}<'],
  ['>Teléfono Soporte<', '>{t.settingsPage?.printPhoneLabel || "Teléfono Soporte"}<'],
  ['>Margen Final (Cola del Recibo)<', '>{t.settingsPage?.printMarginTitle || "Margen Final"}<'],
  ['>Largo del papel sobrante<', '>{t.settingsPage?.printMarginDesc || "Largo del papel sobrante"}<'],
  ['>LÍNEAS<', '>{t.settingsPage?.lines || "LÍNEAS"}<'],
  ['GUARDAR DATOS DE EMPRESA', '{t.settingsPage?.saveCompanyData || "GUARDAR DATOS DE EMPRESA"}'],
  ['>Integración de Bancard (Cobro QR)<', '>{t.settingsPage?.bancardTitle || "Integración de Bancard"}<'],
  ['>Configuración de Credenciales para Cobro Móvil<', '>{t.settingsPage?.bancardDesc || "Configuración de Credenciales"}<'],
  ['>Código de Comercio (Shop ID)<', '>{t.settingsPage?.shopIdLabel || "Código de Comercio"}<'],
  ['>Clave Pública (Public Key)<', '>{t.settingsPage?.publicKeyLabel || "Clave Pública"}<'],
  ['>Clave Privada (Private Key)<', '>{t.settingsPage?.privateKeyLabel || "Clave Privada"}<'],
  ["{isLoadingBancard ? 'GUARDANDO...' : 'GUARDAR CREDENCIALES DE BANCARD'}", "{isLoadingBancard ? (t.settingsPage?.saving || 'GUARDANDO...') : (t.settingsPage?.saveBancard || 'GUARDAR CREDENCIALES DE BANCARD')}"],
  ['>Zona de Estabilización<', '>{t.settingsPage?.syncZoneTitle || "Zona de Estabilización"}<'],
  ['>Solución de Sincronización<', '>{t.settingsPage?.syncZoneDesc || "Solución de Sincronización"}<'],
  ["{isOnline ? 'Conexión Estable' : 'Sin Internet Real'}", "{isOnline ? (t.settingsPage?.connStable || 'Conexión Estable') : (t.settingsPage?.connOffline || 'Sin Internet Real')}"],
  ["{isOnline ? 'La App tiene acceso verificado a los servidores.' : 'Detectamos problemas de conexión. Los datos se guardarán localmente.'}", "{isOnline ? (t.settingsPage?.connStableDesc || 'La App tiene acceso verificado a los servidores.') : (t.settingsPage?.connOfflineDesc || 'Detectamos problemas de conexión. Los datos se guardarán localmente.')}"],
  ["{isSyncing ? 'SINCRONIZANDO...' : 'FORZAR SINCRONIZACIÓN'}", "{isSyncing ? (t.settingsPage?.syncing || 'SINCRONIZANDO...') : (t.settingsPage?.forceSyncBtn || 'FORZAR SINCRONIZACIÓN')}"],
  ['>LIMPIAR COLA<', '>{t.settingsPage?.clearQueueBtn || "LIMPIAR COLA"}<'],
  ['>REPARAR PROBL. SINCRONIZACIÓN<', '>{t.settingsPage?.repairSyncBtn || "REPARAR PROBL. SINCRONIZACIÓN"}<'],
  ['>ACTUALIZACIÓN PROFUNDA<', '>{t.settingsPage?.deepUpdateBtn || "ACTUALIZACIÓN PROFUNDA"}<'],
  ['>* Use "Forzar Sincronización" si sus pagos no aparecen. Use "Reparación Profunda" solo si el problema persiste tras forzar.<', '>{t.settingsPage?.syncWarning || "* Use Forzar Sincronización..."}<'],
  ['>Formato de Moneda<', '>{t.settingsPage?.currencyFormatTitle || "Formato de Moneda"}<'],
  ['>PUNTO DE MIL<', '>{t.settingsPage?.dotFormat || "PUNTO DE MIL"}<'],
  ['>PUNTO DE COMA<', '>{t.settingsPage?.commaFormat || "PUNTO DE COMA"}<'],
  ['>Configuración de Impresora<', '>{t.settingsPage?.printerConfigTitle || "Configuración de Impresora"}<'],
  ["{scanningPrinters ? 'BUSCANDO...' : 'BUSCAR IMPRESORA'}", "{scanningPrinters ? (t.settingsPage?.searching || 'BUSCANDO...') : (t.settingsPage?.searchPrinterBtn || 'BUSCAR IMPRESORA')}"],
  ['>PROBAR IMPRESIÓN<', '>{t.settingsPage?.testPrintBtn || "PROBAR IMPRESIÓN"}<'],
  ['>* Conecte su impresora térmica vía Bluetooth para imprimir recibos automáticamente tras cada cobro.<', '>{t.settingsPage?.printerWarning || "* Conecte su impresora..."}<'],
  ['Vinculado:', '{t.settingsPage?.linked || "Vinculado:"}'],
  ['>Idioma App<', '>{t.settings.language || "Idioma App"}<'],
  ['>País de Operación<', '>{t.settings.country || "País de Operación"}<'],
  ['>Ajusta festivos y formato de moneda.<', '>{t.settings.countryDesc || "Ajusta festivos y formato de moneda."}<'],
  ['GUARDAR Y SALIR', '{t.settingsPage?.saveAndExit || "GUARDAR Y SALIR"}']
];

for (const [from, to] of replacements) {
  compCode = compCode.split(from).join(to);
}

fs.writeFileSync(compPath, compCode, 'utf8');
console.log('Update successful');
